version: '2'
services:
  satisfy:
    image: aseemann/satisfy
    container_name: satisfy
    build:
      context: docker/
    environment:
      - APP_PATH=/var/www/satisfy
      - COMPOSER_HOME=/var/www/satisfy/var/composer
    expose:
      - 80